name: Deploy Hexo Blog

on:
  push:
    branches:
      - dev  # 监听源码分支的变动

permissions:
  contents: write # 必须赋予写权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: dev          # 拉取源码
          submodules: true  # 兼容主题 submodule
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' # 使用Node 14，兼容Hexo 5.x

      - name: Install Hexo 5.x
        run: |
          npm install -g hexo-cli@4.3.0
          npm install hexo@5.4.2 --save

      - name: Install Dependencies
        run: npm install --no-optional

      - name: Build Hexo
        run: hexo generate

      - name: Deploy to Master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # 发布到 master 分支
          commit_message: "Auto deploy: ${{ github.event.head_commit.message }}"
